service: fedeira-investment-services
frameworkVersion: '4'

plugins:
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  tags:
    Project: 'IS'
    Service: 'Investment-services'
    Environment: "${opt:stage, 'dev'}"
  runtime: nodejs18.x
  profile: Developer-PPI
  region: us-east-2
  environment:
    IS_OFFLINE: ${opt:isOffline, 'false'}
    PPI_API_VERSION: ${self:custom.variables.PPI_API_VERSION}
    PPI_API_KEY: ${self:custom.variables.PPI_API_KEY}
    PPI_API_SECRET: ${self:custom.variables.PPI_API_SECRET}
    PPI_AUTHORIZED_CLIENT: ${self:custom.variables.PPI_AUTHORIZED_CLIENT}
    PPI_CLIENT_KEY: ${self:custom.variables.PPI_CLIENT_KEY}
    PPI_ACCOUNT_NUMBER: ${self:custom.variables.PPI_ACCOUNT_NUMBER}
  iam:
    role:
      statements:
        # Permit for ssm operations
        - Effect: 'Allow'
          Action:
            - 'ssm:GetParameter'
          Resource: 'arn:aws:ssm:us-east-2:${env:AWS_ACCOUNT_ID}:parameter/ppi'
        # Permit for dynamodb operations
        - Effect: 'Allow'
          Action:
            - 'dynamodb:Query'
            - 'dynamodb:Scan'
            - 'dynamodb:GetItem'
            - 'dynamodb:PutItem'
            - 'dynamodb:UpdateItem'
            - 'dynamodb:DeleteItem'
          Resource: 'arn:aws:dynamodb:us-east-2:${env:AWS_ACCOUNT_ID}:table/CreditBehavior'
        # Permit for logs operations in cloudwatch
        - Effect: 'Allow'
          Action:
            - 'logs:CreateLogGroup'
            - 'logs:CreateLogStream'
            - 'logs:PutLogEvents'
          Resource: "arn:aws:logs:us-east-2:${env:AWS_ACCOUNT_ID}:log-group:/aws/lambda/fedeira-investment-services:*"
        # Permit for ses operations
        - Effect: 'Allow'
          Action:
            - 'ses:SendEmail'
            - 'ses:SendRawEmail'
            - 'ses:ListIdentities'
          Resource: "arn:aws:ses:us-east-2:${env:AWS_ACCOUNT_ID}:identity/my-secure-domain.com"
functions:
  ppiLogin:
    handler: investment-services/handler.getAvailableBalance
    timeout: 60
    memorySize: 1024
    events:
      - http:
          path: investment/available-balance
          method: get
          cors:
            origin: 'https://my-secure-domain.com'
            headers:
              - Content-Type
            allowCredentials: true

resources:
  Resources:
    CreditBehaviorTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: CreditBehavior
        AttributeDefinitions:
          - AttributeName: nadroCode
            AttributeType: S
        KeySchema:
          - AttributeName: nadroCode
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

  Outputs:
    DynamoDBEndpoint:
      Description: 'DynamoDB Host Endpoint'
      Value: !Sub 'https://dynamodb.${AWS::Region}.amazonaws.com'

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: node20
    platform: node
    exclude: ['aws-sdk']

  dotenv:
    path: .env
    include:
      - DEV_DYNAMODB_ENDPOINT
      - PPP_API_VERSION
      - AWS_ACCOUNT_ID

  variables:
    PPI_API_VERSION: ${ssm:/ppi/apiVersion}
    PPI_API_KEY: ${ssm:/ppi/apiKey}
    PPI_API_SECRET: ${ssm:/ppi/apiSecret}
    PPI_AUTHORIZED_CLIENT: ${ssm:/ppi/authorizedClient}
    PPI_CLIENT_KEY: ${ssm:/ppi/clientKey}
    PPI_ACCOUNT_NUMBER: ${ssm:/ppi/accountNumber}

  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      seed: true
      convertEmptyValues: true
